version: "2"
services:
  server:
    build:
      context: ./server/
    command: npm run start
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3050:3050"
    links:
      - mongo
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  client:
    build:
      context: ./client/
    # command: yarn start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "8080:80"
